In [1]:
import pandas as pd

In [2]:
pd.read_csv('/Users/etienneleconte/Downloads/dota2Dataset/dota2Train.csv')

,-1,223,2,2.1,0,0.1,0.2,0.3,0.4,0.5,...,0.93,0.94,0.95,0.96,0.97,0.98,0.99,0.100,0.101,0.102
0,1,152,2,2,0,0,0,1,0,-1,...,0,0,0,0,0,0,0,0,0,0
1,1,131,2,2,0,0,0,1,0,-1,...,0,0,0,0,0,0,0,0,0,0
2,1,154,2,2,0,0,0,0,0,0,...,-1,0,0,0,0,0,0,0,0,0
3,-1,171,2,3,0,0,0,0,0,-1,...,0,0,0,0,0,0,0,0,0,0
4,1,122,2,3,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92644,-1,154,2,3,1,0,0,-1,0,0,...,0,0,0,0,0,0,0,0,0,0
92645,1,154,2,2,0,0,0,0,-1,0,...,1,0,0,0,0,0,0,0,0,0
92646,1,111,2,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
92647,-1,185,2,2,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
92648,-1,204,2,2,0,-1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0